steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/ankit-44881/hello-repo/hello-image:v3'  # Updated to v3
      - '.'
      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/ankit-44881/hello-repo/hello-image:v3'  # Updated to v3
  
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/hello-world-app2'
      - 'hello-world-container=us-central1-docker.pkg.dev/ankit-44881/hello-repo/hello-image:v3'  # Updated to v3
  
images:
  - 'us-central1-docker.pkg.dev/ankit-44881/hello-repo/hello-image:v3'  # Updated to v3
  
options:
  logging: CLOUD_LOGGING_ONLY
