steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'hello-world-cluster'
      - '--region'
      - 'us-central1'
      - '--project'
      - 'ankit-44881'
    env:
      - 'CLOUDSDK_GET_CREDENTIALS_OPTS=--quiet'  # Optional: suppresses output

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/hello-world-app2'
      - 'hello-world-container=us-central1-docker.pkg.dev/ankit-44881/hello-repo/hello-image:v3'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/hello-world-app'

options:
  logging: CLOUD_LOGGING_ONLY
