steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/ankit-44881/hello-world-repo/hello-world-app:v2, '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south2-docker.pkg.dev/ankit-44881/hello-world-repo/hello-world-app:v2']

  
  
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-south2-docker.pkg.dev/ankit-44881/hello-world-repo/hello-world-app:v2'
