apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world2
  template:
    metadata:
      labels:
        app: hello-world2
    spec:
      containers:
      - name: hello-world-container
        image: us-central1-docker.pkg.dev/ankit-44881/hello-repo/hello-image:v2        
        ports:
        - containerPort: 8080

